version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polly
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  bot:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - ENV_FILE=.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pg_data: